Lab 1
akzhukov/GPU_Labs pull request #1
Opened 2021-03-14 16:32 UTC by akzhukov

2021-03-25 18:48 UTC, Kauter1989 requested changes

2021-03-25 18:48 UTC, Kauter1989 commented on lab1/kernel.cu
> +	dim3 blocks((size) / threads.x + 1, (size) / threads.y + 1);
Неверно посчитано

2021-03-25 18:48 UTC, Kauter1989 commented on lab1/kernel.cu
> +__global__ void matrixMult(double* A, double* B, double* C, size_t size)
Объясните, может ли повлиять в вашем коде restrict на производительность

2021-03-31 23:39 UTC, akzhukov commented on lab1/kernel.cu
> +__global__ void matrixMult(double* A, double* B, double* C, size_t size)
Поскольку память, на которую указывают A,B,C по смыслу задачи не перекрывается, то имеет смысл указать на это компилятору, чтобы помочь ему оптимизировать данный код. Поэтому это может повлиять на производительность.

2021-03-31 23:39 UTC, akzhukov commented on lab1/kernel.cu
> +	dim3 blocks((size) / threads.x + 1, (size) / threads.y + 1);
Исправлено

2021-04-06 00:30 UTC, merged

2021-04-18 12:21 UTC, Kauter1989 commented
Все равно неверно посчитано, надо оптимальнее; более того, мы это проходили
на лекции

вт, 6 апр. 2021 г. в 03:30, Zhukov Alexander ***@***.***>:

> Merged #1 <https://github.com/akzhukov/GPU_Labs/pull/1> into main.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/akzhukov/GPU_Labs/pull/1#event-4553932613>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIUVEKPAD536JMP2QFX4JUTTHJI2TANCNFSM4ZFEKE6Q>
> .
>